config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :forums
  get 'area_user_relation/create'

  get 'area_user_relation/destroy'

  resources :areas
  get 'static_pages/home'
  get 'static_pages/help'
  get  'static_pages/home'
  get  'static_pages/help'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  root 'static_pages#home'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
    has_many :users
    has_many :forums
    has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "400x400" }
    validates_attachment :image, :presence => true,
        :content_type => { content_type: ["image/jpeg","image/jpg","image/png","image/gif"] },
        :size => { :in => 0..100.megabytes }
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :image)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true, html: { multipart: true })  do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :area_name %>
    
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Edit Area</h1>
<div class="col-md-10 col-md-offset-1">
    <%= form_for @area, html: { multipart: true } do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, id: :area_name, class: 'form-control' %>
        <%= f.file_field :image %>
    
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
</div>
<div class="col-md-12"></div>
<%= link_to 'Back', areas_path ,:class => "col-md-12"%>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Areas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= link_to image_tag(area.image.url(:med)), area.image.url %></td>
        <td><%= area.name %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>
<div class="col-md-10 col-md-offset-1">
    <%= form_for @area, html: { multipart: true } do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, id: :area_name, class: 'form-control' %>
        <%= f.file_field :image %>
    
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
</div>
<div class="col-md-12"></div>
<%= link_to 'Back', areas_path ,:class => "col-md-12"%>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "banner_container container">
  <div class = "banner_text col-md-12"><%= @area.name %></div>
  <div class  = "filter"></div>
    <div class = "banner"><%= image_tag(@area.image.url)%></div>
</div>

<% @area.forums.each do |forum| %>
      
        <%= forum.name %>
        <%= forum.describtion %>

      </tr>
    <% end %>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>